from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server import util


class Channel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, peers=None):  # noqa: E501
        """Channel - a model defined in OpenAPI

        :param id: The id of this Channel.  # noqa: E501
        :type id: str
        :param description: The description of this Channel.  # noqa: E501
        :type description: str
        :param peers: The peers of this Channel.  # noqa: E501
        :type peers: List[str]
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'peers': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'peers': 'peers'
        }

        self._id = id
        self._description = description
        self._peers = peers

    @classmethod
    def from_dict(cls, dikt) -> 'Channel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The channel of this Channel.  # noqa: E501
        :rtype: Channel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Channel.


        :return: The id of this Channel.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Channel.


        :param id: The id of this Channel.
        :type id: str
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Channel.

        A free form field to put a human readable description  # noqa: E501

        :return: The description of this Channel.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Channel.

        A free form field to put a human readable description  # noqa: E501

        :param description: The description of this Channel.
        :type description: str
        """

        self._description = description

    @property
    def peers(self) -> List[str]:
        """Gets the peers of this Channel.

        The ids of the peers in this channel. Should refer to ids of segments  # noqa: E501

        :return: The peers of this Channel.
        :rtype: List[str]
        """
        return self._peers

    @peers.setter
    def peers(self, peers: List[str]):
        """Sets the peers of this Channel.

        The ids of the peers in this channel. Should refer to ids of segments  # noqa: E501

        :param peers: The peers of this Channel.
        :type peers: List[str]
        """
        if peers is None:
            raise ValueError("Invalid value for `peers`, must not be `None`")  # noqa: E501
        if peers is not None and len(peers) < 2:
            raise ValueError("Invalid value for `peers`, number of items must be greater than or equal to `2`")  # noqa: E501

        self._peers = peers
