from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.repeat_segments_inner import RepeatSegmentsInner
from nexussim_server import util

from nexussim_server.models.repeat_segments_inner import RepeatSegmentsInner  # noqa: E501

class Choice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, segments=None, weights=None):  # noqa: E501
        """Choice - a model defined in OpenAPI

        :param segments: The segments of this Choice.  # noqa: E501
        :type segments: List[RepeatSegmentsInner]
        :param weights: The weights of this Choice.  # noqa: E501
        :type weights: List[float]
        """
        self.openapi_types = {
            'segments': List[RepeatSegmentsInner],
            'weights': List[float]
        }

        self.attribute_map = {
            'segments': 'segments',
            'weights': 'weights'
        }

        self._segments = segments
        self._weights = weights

    @classmethod
    def from_dict(cls, dikt) -> 'Choice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The choice of this Choice.  # noqa: E501
        :rtype: Choice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def segments(self) -> List[RepeatSegmentsInner]:
        """Gets the segments of this Choice.

        List of segments to choose from  # noqa: E501

        :return: The segments of this Choice.
        :rtype: List[RepeatSegmentsInner]
        """
        return self._segments

    @segments.setter
    def segments(self, segments: List[RepeatSegmentsInner]):
        """Sets the segments of this Choice.

        List of segments to choose from  # noqa: E501

        :param segments: The segments of this Choice.
        :type segments: List[RepeatSegmentsInner]
        """
        if segments is None:
            raise ValueError("Invalid value for `segments`, must not be `None`")  # noqa: E501
        if segments is not None and len(segments) < 1:
            raise ValueError("Invalid value for `segments`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._segments = segments

    @property
    def weights(self) -> List[float]:
        """Gets the weights of this Choice.

        List of weights for each segment. Should be same length as segments.  # noqa: E501

        :return: The weights of this Choice.
        :rtype: List[float]
        """
        return self._weights

    @weights.setter
    def weights(self, weights: List[float]):
        """Sets the weights of this Choice.

        List of weights for each segment. Should be same length as segments.  # noqa: E501

        :param weights: The weights of this Choice.
        :type weights: List[float]
        """
        if weights is not None and len(weights) < 1:
            raise ValueError("Invalid value for `weights`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._weights = weights
