from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
import re
from nexussim_server import util

import re  # noqa: E501

class Compute(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, cpus=None, cpu_speed=None, mem=None, disk=None):  # noqa: E501
        """Compute - a model defined in OpenAPI

        :param id: The id of this Compute.  # noqa: E501
        :type id: str
        :param description: The description of this Compute.  # noqa: E501
        :type description: str
        :param cpus: The cpus of this Compute.  # noqa: E501
        :type cpus: int
        :param cpu_speed: The cpu_speed of this Compute.  # noqa: E501
        :type cpu_speed: str
        :param mem: The mem of this Compute.  # noqa: E501
        :type mem: str
        :param disk: The disk of this Compute.  # noqa: E501
        :type disk: str
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'cpus': int,
            'cpu_speed': str,
            'mem': str,
            'disk': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'cpus': 'cpus',
            'cpu_speed': 'cpu_speed',
            'mem': 'mem',
            'disk': 'disk'
        }

        self._id = id
        self._description = description
        self._cpus = cpus
        self._cpu_speed = cpu_speed
        self._mem = mem
        self._disk = disk

    @classmethod
    def from_dict(cls, dikt) -> 'Compute':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The compute of this Compute.  # noqa: E501
        :rtype: Compute
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Compute.

        The id of the node  # noqa: E501

        :return: The id of this Compute.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Compute.

        The id of the node  # noqa: E501

        :param id: The id of this Compute.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Compute.

        A free form field to put a human readable description  # noqa: E501

        :return: The description of this Compute.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Compute.

        A free form field to put a human readable description  # noqa: E501

        :param description: The description of this Compute.
        :type description: str
        """

        self._description = description

    @property
    def cpus(self) -> int:
        """Gets the cpus of this Compute.

        Number of CPUs in this node  # noqa: E501

        :return: The cpus of this Compute.
        :rtype: int
        """
        return self._cpus

    @cpus.setter
    def cpus(self, cpus: int):
        """Sets the cpus of this Compute.

        Number of CPUs in this node  # noqa: E501

        :param cpus: The cpus of this Compute.
        :type cpus: int
        """
        if cpus is not None and cpus < 1:  # noqa: E501
            raise ValueError("Invalid value for `cpus`, must be a value greater than or equal to `1`")  # noqa: E501

        self._cpus = cpus

    @property
    def cpu_speed(self) -> str:
        """Gets the cpu_speed of this Compute.

        Frequency in Herz  # noqa: E501

        :return: The cpu_speed of this Compute.
        :rtype: str
        """
        return self._cpu_speed

    @cpu_speed.setter
    def cpu_speed(self, cpu_speed: str):
        """Sets the cpu_speed of this Compute.

        Frequency in Herz  # noqa: E501

        :param cpu_speed: The cpu_speed of this Compute.
        :type cpu_speed: str
        """
        if cpu_speed is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [TGMk]?Hz$', cpu_speed):  # noqa: E501
            raise ValueError(r"Invalid value for `cpu_speed`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [TGMk]?Hz$/`")  # noqa: E501

        self._cpu_speed = cpu_speed

    @property
    def mem(self) -> str:
        """Gets the mem of this Compute.

        Amount of memory  # noqa: E501

        :return: The mem of this Compute.
        :rtype: str
        """
        return self._mem

    @mem.setter
    def mem(self, mem: str):
        """Sets the mem of this Compute.

        Amount of memory  # noqa: E501

        :param mem: The mem of this Compute.
        :type mem: str
        """
        if mem is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$', mem):  # noqa: E501
            raise ValueError(r"Invalid value for `mem`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$/`")  # noqa: E501

        self._mem = mem

    @property
    def disk(self) -> str:
        """Gets the disk of this Compute.

        Amount of memory  # noqa: E501

        :return: The disk of this Compute.
        :rtype: str
        """
        return self._disk

    @disk.setter
    def disk(self, disk: str):
        """Sets the disk of this Compute.

        Amount of memory  # noqa: E501

        :param disk: The disk of this Compute.
        :type disk: str
        """
        if disk is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$', disk):  # noqa: E501
            raise ValueError(r"Invalid value for `disk`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$/`")  # noqa: E501

        self._disk = disk
