from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
#from nexussim_server.models.choice import Choice
#from nexussim_server.models.concurrent import Concurrent
from nexussim_server.models.load import Load
#from nexussim_server.models.repeat import Repeat
from nexussim_server.models.segment import Segment
from nexussim_server.models.segment_emits import SegmentEmits
from nexussim_server.models.segment_stops_after import SegmentStopsAfter
from nexussim_server import util

#from nexussim_server.models.choice import Choice  # noqa: E501
#from nexussim_server.models.concurrent import Concurrent  # noqa: E501
from nexussim_server.models.load import Load  # noqa: E501
#from nexussim_server.models.repeat import Repeat  # noqa: E501
from nexussim_server.models.segment import Segment  # noqa: E501
from nexussim_server.models.segment_emits import SegmentEmits  # noqa: E501
from nexussim_server.models.segment_stops_after import SegmentStopsAfter  # noqa: E501

class ConcurrentSegmentsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, load=None, emits=None, stops_after=None, n_times=-1, segments=None, weights=None):  # noqa: E501
        """ConcurrentSegmentsInner - a model defined in OpenAPI

        :param id: The id of this ConcurrentSegmentsInner.  # noqa: E501
        :type id: str
        :param description: The description of this ConcurrentSegmentsInner.  # noqa: E501
        :type description: str
        :param load: The load of this ConcurrentSegmentsInner.  # noqa: E501
        :type load: Load
        :param emits: The emits of this ConcurrentSegmentsInner.  # noqa: E501
        :type emits: SegmentEmits
        :param stops_after: The stops_after of this ConcurrentSegmentsInner.  # noqa: E501
        :type stops_after: SegmentStopsAfter
        :param n_times: The n_times of this ConcurrentSegmentsInner.  # noqa: E501
        :type n_times: float
        :param segments: The segments of this ConcurrentSegmentsInner.  # noqa: E501
        :type segments: List['ConcurrentSegmentsInner']
        :param weights: The weights of this ConcurrentSegmentsInner.  # noqa: E501
        :type weights: List[float]
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'load': Load,
            'emits': SegmentEmits,
            'stops_after': SegmentStopsAfter,
            'n_times': float,
            'segments': List['ConcurrentSegmentsInner'],
            'weights': List[float]
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'load': 'load',
            'emits': 'emits',
            'stops_after': 'stops_after',
            'n_times': 'n_times',
            'segments': 'segments',
            'weights': 'weights'
        }

        self._id = id
        self._description = description
        self._load = load
        self._emits = emits
        self._stops_after = stops_after
        self._n_times = n_times
        self._segments = segments
        self._weights = weights

    @classmethod
    def from_dict(cls, dikt) -> 'ConcurrentSegmentsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The concurrent_segments_inner of this ConcurrentSegmentsInner.  # noqa: E501
        :rtype: ConcurrentSegmentsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ConcurrentSegmentsInner.


        :return: The id of this ConcurrentSegmentsInner.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ConcurrentSegmentsInner.


        :param id: The id of this ConcurrentSegmentsInner.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this ConcurrentSegmentsInner.

        A free form field to put a human readable description  # noqa: E501

        :return: The description of this ConcurrentSegmentsInner.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ConcurrentSegmentsInner.

        A free form field to put a human readable description  # noqa: E501

        :param description: The description of this ConcurrentSegmentsInner.
        :type description: str
        """

        self._description = description

    @property
    def load(self) -> Load:
        """Gets the load of this ConcurrentSegmentsInner.


        :return: The load of this ConcurrentSegmentsInner.
        :rtype: Load
        """
        return self._load

    @load.setter
    def load(self, load: Load):
        """Sets the load of this ConcurrentSegmentsInner.


        :param load: The load of this ConcurrentSegmentsInner.
        :type load: Load
        """

        self._load = load

    @property
    def emits(self) -> SegmentEmits:
        """Gets the emits of this ConcurrentSegmentsInner.


        :return: The emits of this ConcurrentSegmentsInner.
        :rtype: SegmentEmits
        """
        return self._emits

    @emits.setter
    def emits(self, emits: SegmentEmits):
        """Sets the emits of this ConcurrentSegmentsInner.


        :param emits: The emits of this ConcurrentSegmentsInner.
        :type emits: SegmentEmits
        """

        self._emits = emits

    @property
    def stops_after(self) -> SegmentStopsAfter:
        """Gets the stops_after of this ConcurrentSegmentsInner.


        :return: The stops_after of this ConcurrentSegmentsInner.
        :rtype: SegmentStopsAfter
        """
        return self._stops_after

    @stops_after.setter
    def stops_after(self, stops_after: SegmentStopsAfter):
        """Sets the stops_after of this ConcurrentSegmentsInner.


        :param stops_after: The stops_after of this ConcurrentSegmentsInner.
        :type stops_after: SegmentStopsAfter
        """
        if stops_after is None:
            raise ValueError("Invalid value for `stops_after`, must not be `None`")  # noqa: E501

        self._stops_after = stops_after

    @property
    def n_times(self) -> float:
        """Gets the n_times of this ConcurrentSegmentsInner.

        The number of times to repeat.  Use -1 for infinite repetitions.  # noqa: E501

        :return: The n_times of this ConcurrentSegmentsInner.
        :rtype: float
        """
        return self._n_times

    @n_times.setter
    def n_times(self, n_times: float):
        """Sets the n_times of this ConcurrentSegmentsInner.

        The number of times to repeat.  Use -1 for infinite repetitions.  # noqa: E501

        :param n_times: The n_times of this ConcurrentSegmentsInner.
        :type n_times: float
        """

        self._n_times = n_times

    @property
    def segments(self) -> List['ConcurrentSegmentsInner']:
        """Gets the segments of this ConcurrentSegmentsInner.

        List of segments to run concurrently  # noqa: E501

        :return: The segments of this ConcurrentSegmentsInner.
        :rtype: List['ConcurrentSegmentsInner']
        """
        return self._segments

    @segments.setter
    def segments(self, segments: List['ConcurrentSegmentsInner']):
        """Sets the segments of this ConcurrentSegmentsInner.

        List of segments to run concurrently  # noqa: E501

        :param segments: The segments of this ConcurrentSegmentsInner.
        :type segments: List['ConcurrentSegmentsInner']
        """
        if segments is None:
            raise ValueError("Invalid value for `segments`, must not be `None`")  # noqa: E501
        if segments is not None and len(segments) < 1:
            raise ValueError("Invalid value for `segments`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._segments = segments

    @property
    def weights(self) -> List[float]:
        """Gets the weights of this ConcurrentSegmentsInner.

        List of weights for each segment. Should be same length as segments.  # noqa: E501

        :return: The weights of this ConcurrentSegmentsInner.
        :rtype: List[float]
        """
        return self._weights

    @weights.setter
    def weights(self, weights: List[float]):
        """Sets the weights of this ConcurrentSegmentsInner.

        List of weights for each segment. Should be same length as segments.  # noqa: E501

        :param weights: The weights of this ConcurrentSegmentsInner.
        :type weights: List[float]
        """
        if weights is not None and len(weights) < 1:
            raise ValueError("Invalid value for `weights`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._weights = weights
