from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.concurrent_segments_inner import ConcurrentSegmentsInner
from nexussim_server import util

from nexussim_server.models.concurrent_segments_inner import ConcurrentSegmentsInner  # noqa: E501

class Concurrent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, segments=None):  # noqa: E501
        """Concurrent - a model defined in OpenAPI

        :param segments: The segments of this Concurrent.  # noqa: E501
        :type segments: List[ConcurrentSegmentsInner]
        """
        self.openapi_types = {
            'segments': List[ConcurrentSegmentsInner]
        }

        self.attribute_map = {
            'segments': 'segments'
        }

        self._segments = segments

    @classmethod
    def from_dict(cls, dikt) -> 'Concurrent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The concurrent of this Concurrent.  # noqa: E501
        :rtype: Concurrent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def segments(self) -> List[ConcurrentSegmentsInner]:
        """Gets the segments of this Concurrent.

        List of segments to run concurrently  # noqa: E501

        :return: The segments of this Concurrent.
        :rtype: List[ConcurrentSegmentsInner]
        """
        return self._segments

    @segments.setter
    def segments(self, segments: List[ConcurrentSegmentsInner]):
        """Sets the segments of this Concurrent.

        List of segments to run concurrently  # noqa: E501

        :param segments: The segments of this Concurrent.
        :type segments: List[ConcurrentSegmentsInner]
        """
        if segments is None:
            raise ValueError("Invalid value for `segments`, must not be `None`")  # noqa: E501
        if segments is not None and len(segments) < 1:
            raise ValueError("Invalid value for `segments`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._segments = segments
