from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
import re
from nexussim_server import util

import re  # noqa: E501

class Load(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, memory=None, cpu_load=None, duration=None):  # noqa: E501
        """Load - a model defined in OpenAPI

        :param memory: The memory of this Load.  # noqa: E501
        :type memory: str
        :param cpu_load: The cpu_load of this Load.  # noqa: E501
        :type cpu_load: float
        :param duration: The duration of this Load.  # noqa: E501
        :type duration: str
        """
        self.openapi_types = {
            'memory': str,
            'cpu_load': float,
            'duration': str
        }

        self.attribute_map = {
            'memory': 'memory',
            'cpu_load': 'cpu_load',
            'duration': 'duration'
        }

        self._memory = memory
        self._cpu_load = cpu_load
        self._duration = duration

    @classmethod
    def from_dict(cls, dikt) -> 'Load':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The load of this Load.  # noqa: E501
        :rtype: Load
        """
        return util.deserialize_model(dikt, cls)

    @property
    def memory(self) -> str:
        """Gets the memory of this Load.

        Amount of memory  # noqa: E501

        :return: The memory of this Load.
        :rtype: str
        """
        return self._memory

    @memory.setter
    def memory(self, memory: str):
        """Sets the memory of this Load.

        Amount of memory  # noqa: E501

        :param memory: The memory of this Load.
        :type memory: str
        """
        if memory is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$', memory):  # noqa: E501
            raise ValueError(r"Invalid value for `memory`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$/`")  # noqa: E501

        self._memory = memory

    @property
    def cpu_load(self) -> float:
        """Gets the cpu_load of this Load.


        :return: The cpu_load of this Load.
        :rtype: float
        """
        return self._cpu_load

    @cpu_load.setter
    def cpu_load(self, cpu_load: float):
        """Sets the cpu_load of this Load.


        :param cpu_load: The cpu_load of this Load.
        :type cpu_load: float
        """

        self._cpu_load = cpu_load

    @property
    def duration(self) -> str:
        """Gets the duration of this Load.

        Absolute time duration  # noqa: E501

        :return: The duration of this Load.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this Load.

        Absolute time duration  # noqa: E501

        :param duration: The duration of this Load.
        :type duration: str
        """
        if duration is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [mun]?s$', duration):  # noqa: E501
            raise ValueError(r"Invalid value for `duration`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [mun]?s$/`")  # noqa: E501

        self._duration = duration
