from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
import re
from nexussim_server import util

import re  # noqa: E501

class Network(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, peers=None, bandwidth=None, latency=None, local=False):  # noqa: E501
        """Network - a model defined in OpenAPI

        :param id: The id of this Network.  # noqa: E501
        :type id: str
        :param description: The description of this Network.  # noqa: E501
        :type description: str
        :param peers: The peers of this Network.  # noqa: E501
        :type peers: List[str]
        :param bandwidth: The bandwidth of this Network.  # noqa: E501
        :type bandwidth: str
        :param latency: The latency of this Network.  # noqa: E501
        :type latency: str
        :param local: The local of this Network.  # noqa: E501
        :type local: bool
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'peers': List[str],
            'bandwidth': str,
            'latency': str,
            'local': bool
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'peers': 'peers',
            'bandwidth': 'bandwidth',
            'latency': 'latency',
            'local': 'local'
        }

        self._id = id
        self._description = description
        self._peers = peers
        self._bandwidth = bandwidth
        self._latency = latency
        self._local = local

    @classmethod
    def from_dict(cls, dikt) -> 'Network':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The network of this Network.  # noqa: E501
        :rtype: Network
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Network.

        The identifier for this network  # noqa: E501

        :return: The id of this Network.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Network.

        The identifier for this network  # noqa: E501

        :param id: The id of this Network.
        :type id: str
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Network.

        A free form field to put a human readable description  # noqa: E501

        :return: The description of this Network.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Network.

        A free form field to put a human readable description  # noqa: E501

        :param description: The description of this Network.
        :type description: str
        """

        self._description = description

    @property
    def peers(self) -> List[str]:
        """Gets the peers of this Network.

        The id of the peers in this link. Should refer to ids of computes  # noqa: E501

        :return: The peers of this Network.
        :rtype: List[str]
        """
        return self._peers

    @peers.setter
    def peers(self, peers: List[str]):
        """Sets the peers of this Network.

        The id of the peers in this link. Should refer to ids of computes  # noqa: E501

        :param peers: The peers of this Network.
        :type peers: List[str]
        """
        if peers is None:
            raise ValueError("Invalid value for `peers`, must not be `None`")  # noqa: E501

        self._peers = peers

    @property
    def bandwidth(self) -> str:
        """Gets the bandwidth of this Network.

        Speed of data transmission  # noqa: E501

        :return: The bandwidth of this Network.
        :rtype: str
        """
        return self._bandwidth

    @bandwidth.setter
    def bandwidth(self, bandwidth: str):
        """Sets the bandwidth of this Network.

        Speed of data transmission  # noqa: E501

        :param bandwidth: The bandwidth of this Network.
        :type bandwidth: str
        """
        if bandwidth is None:
            raise ValueError("Invalid value for `bandwidth`, must not be `None`")  # noqa: E501
        if bandwidth is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([TGMK]i?)?[Bb]ps$', bandwidth):  # noqa: E501
            raise ValueError(r"Invalid value for `bandwidth`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([TGMK]i?)?[Bb]ps$/`")  # noqa: E501

        self._bandwidth = bandwidth

    @property
    def latency(self) -> str:
        """Gets the latency of this Network.

        Absolute time duration  # noqa: E501

        :return: The latency of this Network.
        :rtype: str
        """
        return self._latency

    @latency.setter
    def latency(self, latency: str):
        """Sets the latency of this Network.

        Absolute time duration  # noqa: E501

        :param latency: The latency of this Network.
        :type latency: str
        """
        if latency is None:
            raise ValueError("Invalid value for `latency`, must not be `None`")  # noqa: E501
        if latency is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [mun]?s$', latency):  # noqa: E501
            raise ValueError(r"Invalid value for `latency`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [mun]?s$/`")  # noqa: E501

        self._latency = latency

    @property
    def local(self) -> bool:
        """Gets the local of this Network.

        Denotes whether the peers in this link can only access each other, or to a global external network.   # noqa: E501

        :return: The local of this Network.
        :rtype: bool
        """
        return self._local

    @local.setter
    def local(self, local: bool):
        """Sets the local of this Network.

        Denotes whether the peers in this link can only access each other, or to a global external network.   # noqa: E501

        :param local: The local of this Network.
        :type local: bool
        """

        self._local = local
