from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.repeat_segments_inner import RepeatSegmentsInner
from nexussim_server import util

from nexussim_server.models.repeat_segments_inner import RepeatSegmentsInner  # noqa: E501

class Repeat(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, n_times=-1, segments=None):  # noqa: E501
        """Repeat - a model defined in OpenAPI

        :param n_times: The n_times of this Repeat.  # noqa: E501
        :type n_times: float
        :param segments: The segments of this Repeat.  # noqa: E501
        :type segments: List[RepeatSegmentsInner]
        """
        self.openapi_types = {
            'n_times': float,
            'segments': List[RepeatSegmentsInner]
        }

        self.attribute_map = {
            'n_times': 'n_times',
            'segments': 'segments'
        }

        self._n_times = n_times
        self._segments = segments

    @classmethod
    def from_dict(cls, dikt) -> 'Repeat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The repeat of this Repeat.  # noqa: E501
        :rtype: Repeat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def n_times(self) -> float:
        """Gets the n_times of this Repeat.

        The number of times to repeat.  Use -1 for infinite repetitions.  # noqa: E501

        :return: The n_times of this Repeat.
        :rtype: float
        """
        return self._n_times

    @n_times.setter
    def n_times(self, n_times: float):
        """Sets the n_times of this Repeat.

        The number of times to repeat.  Use -1 for infinite repetitions.  # noqa: E501

        :param n_times: The n_times of this Repeat.
        :type n_times: float
        """

        self._n_times = n_times

    @property
    def segments(self) -> List[RepeatSegmentsInner]:
        """Gets the segments of this Repeat.

        The segments to repeat. If more than one, a sequence will be used.  # noqa: E501

        :return: The segments of this Repeat.
        :rtype: List[RepeatSegmentsInner]
        """
        return self._segments

    @segments.setter
    def segments(self, segments: List[RepeatSegmentsInner]):
        """Sets the segments of this Repeat.

        The segments to repeat. If more than one, a sequence will be used.  # noqa: E501

        :param segments: The segments of this Repeat.
        :type segments: List[RepeatSegmentsInner]
        """
        if segments is None:
            raise ValueError("Invalid value for `segments`, must not be `None`")  # noqa: E501
        if segments is not None and len(segments) < 1:
            raise ValueError("Invalid value for `segments`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._segments = segments
