from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
import re
from nexussim_server import util

import re  # noqa: E501

class SegmentStopsAfter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, time=None, cycles=None, event=None):  # noqa: E501
        """SegmentStopsAfter - a model defined in OpenAPI

        :param time: The time of this SegmentStopsAfter.  # noqa: E501
        :type time: str
        :param cycles: The cycles of this SegmentStopsAfter.  # noqa: E501
        :type cycles: int
        :param event: The event of this SegmentStopsAfter.  # noqa: E501
        :type event: bool
        """
        self.openapi_types = {
            'time': str,
            'cycles': int,
            'event': bool
        }

        self.attribute_map = {
            'time': 'time',
            'cycles': 'cycles',
            'event': 'event'
        }

        self._time = time
        self._cycles = cycles
        self._event = event

    @classmethod
    def from_dict(cls, dikt) -> 'SegmentStopsAfter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The segment_stops_after of this SegmentStopsAfter.  # noqa: E501
        :rtype: SegmentStopsAfter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> str:
        """Gets the time of this SegmentStopsAfter.

        Absolute time duration  # noqa: E501

        :return: The time of this SegmentStopsAfter.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this SegmentStopsAfter.

        Absolute time duration  # noqa: E501

        :param time: The time of this SegmentStopsAfter.
        :type time: str
        """
        if time is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [mun]?s$', time):  # noqa: E501
            raise ValueError(r"Invalid value for `time`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) [mun]?s$/`")  # noqa: E501

        self._time = time

    @property
    def cycles(self) -> int:
        """Gets the cycles of this SegmentStopsAfter.


        :return: The cycles of this SegmentStopsAfter.
        :rtype: int
        """
        return self._cycles

    @cycles.setter
    def cycles(self, cycles: int):
        """Sets the cycles of this SegmentStopsAfter.


        :param cycles: The cycles of this SegmentStopsAfter.
        :type cycles: int
        """

        self._cycles = cycles

    @property
    def event(self) -> bool:
        """Gets the event of this SegmentStopsAfter.


        :return: The event of this SegmentStopsAfter.
        :rtype: bool
        """
        return self._event

    @event.setter
    def event(self, event: bool):
        """Sets the event of this SegmentStopsAfter.


        :param event: The event of this SegmentStopsAfter.
        :type event: bool
        """

        self._event = event
