from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.segment_emits_target import SegmentEmitsTarget
import re
from nexussim_server import util

from nexussim_server.models.segment_emits_target import SegmentEmitsTarget  # noqa: E501
import re  # noqa: E501

class SegmentEmits(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, size=None, target=None, when=None):  # noqa: E501
        """SegmentEmits - a model defined in OpenAPI

        :param size: The size of this SegmentEmits.  # noqa: E501
        :type size: str
        :param target: The target of this SegmentEmits.  # noqa: E501
        :type target: SegmentEmitsTarget
        :param when: The when of this SegmentEmits.  # noqa: E501
        :type when: str
        """
        self.openapi_types = {
            'size': str,
            'target': SegmentEmitsTarget,
            'when': str
        }

        self.attribute_map = {
            'size': 'size',
            'target': 'target',
            'when': 'when'
        }

        self._size = size
        self._target = target
        self._when = when

    @classmethod
    def from_dict(cls, dikt) -> 'SegmentEmits':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The segment_emits of this SegmentEmits.  # noqa: E501
        :rtype: SegmentEmits
        """
        return util.deserialize_model(dikt, cls)

    @property
    def size(self) -> str:
        """Gets the size of this SegmentEmits.

        Amount of memory  # noqa: E501

        :return: The size of this SegmentEmits.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this SegmentEmits.

        Amount of memory  # noqa: E501

        :param size: The size of this SegmentEmits.
        :type size: str
        """
        if size is not None and not re.search(r'^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$', size):  # noqa: E501
            raise ValueError(r"Invalid value for `size`, must be a follow pattern or equal to `/^([1-9]\d{0,9}(\.\d{1,3})?|0\.\d{1,3}) ([GM]i?|k|Ki)?B$/`")  # noqa: E501

        self._size = size

    @property
    def target(self) -> SegmentEmitsTarget:
        """Gets the target of this SegmentEmits.


        :return: The target of this SegmentEmits.
        :rtype: SegmentEmitsTarget
        """
        return self._target

    @target.setter
    def target(self, target: SegmentEmitsTarget):
        """Sets the target of this SegmentEmits.


        :param target: The target of this SegmentEmits.
        :type target: SegmentEmitsTarget
        """

        self._target = target

    @property
    def when(self) -> str:
        """Gets the when of this SegmentEmits.

        When the emission takes place  # noqa: E501

        :return: The when of this SegmentEmits.
        :rtype: str
        """
        return self._when

    @when.setter
    def when(self, when: str):
        """Sets the when of this SegmentEmits.

        When the emission takes place  # noqa: E501

        :param when: The when of this SegmentEmits.
        :type when: str
        """
        allowed_values = ["on_start", "on_finish"]  # noqa: E501
        if when not in allowed_values:
            raise ValueError(
                "Invalid value for `when` ({0}), must be one of {1}"
                .format(when, allowed_values)
            )

        self._when = when
