from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.load import Load
from nexussim_server.models.segment_emits import SegmentEmits
from nexussim_server.models.segment_stops_after import SegmentStopsAfter
from nexussim_server import util

from nexussim_server.models.load import Load  # noqa: E501
from nexussim_server.models.segment_emits import SegmentEmits  # noqa: E501
from nexussim_server.models.segment_stops_after import SegmentStopsAfter  # noqa: E501

class Segment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, load=None, emits=None, stops_after=None):  # noqa: E501
        """Segment - a model defined in OpenAPI

        :param id: The id of this Segment.  # noqa: E501
        :type id: str
        :param description: The description of this Segment.  # noqa: E501
        :type description: str
        :param load: The load of this Segment.  # noqa: E501
        :type load: Load
        :param emits: The emits of this Segment.  # noqa: E501
        :type emits: SegmentEmits
        :param stops_after: The stops_after of this Segment.  # noqa: E501
        :type stops_after: SegmentStopsAfter
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'load': Load,
            'emits': SegmentEmits,
            'stops_after': SegmentStopsAfter
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'load': 'load',
            'emits': 'emits',
            'stops_after': 'stops_after'
        }

        self._id = id
        self._description = description
        self._load = load
        self._emits = emits
        self._stops_after = stops_after

    @classmethod
    def from_dict(cls, dikt) -> 'Segment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The segment of this Segment.  # noqa: E501
        :rtype: Segment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Segment.


        :return: The id of this Segment.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Segment.


        :param id: The id of this Segment.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Segment.

        A free form field to put a human readable description  # noqa: E501

        :return: The description of this Segment.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Segment.

        A free form field to put a human readable description  # noqa: E501

        :param description: The description of this Segment.
        :type description: str
        """

        self._description = description

    @property
    def load(self) -> Load:
        """Gets the load of this Segment.


        :return: The load of this Segment.
        :rtype: Load
        """
        return self._load

    @load.setter
    def load(self, load: Load):
        """Sets the load of this Segment.


        :param load: The load of this Segment.
        :type load: Load
        """

        self._load = load

    @property
    def emits(self) -> SegmentEmits:
        """Gets the emits of this Segment.


        :return: The emits of this Segment.
        :rtype: SegmentEmits
        """
        return self._emits

    @emits.setter
    def emits(self, emits: SegmentEmits):
        """Sets the emits of this Segment.


        :param emits: The emits of this Segment.
        :type emits: SegmentEmits
        """

        self._emits = emits

    @property
    def stops_after(self) -> SegmentStopsAfter:
        """Gets the stops_after of this Segment.


        :return: The stops_after of this Segment.
        :rtype: SegmentStopsAfter
        """
        return self._stops_after

    @stops_after.setter
    def stops_after(self, stops_after: SegmentStopsAfter):
        """Sets the stops_after of this Segment.


        :param stops_after: The stops_after of this Segment.
        :type stops_after: SegmentStopsAfter
        """
        if stops_after is None:
            raise ValueError("Invalid value for `stops_after`, must not be `None`")  # noqa: E501

        self._stops_after = stops_after
