from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server import util


class SegmentEmitsTarget(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """SegmentEmitsTarget - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SegmentEmitsTarget':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The segment_emits_target of this SegmentEmitsTarget.  # noqa: E501
        :rtype: SegmentEmitsTarget
        """
        return util.deserialize_model(dikt, cls)
