from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.compute import Compute
from nexussim_server.models.network import Network
from nexussim_server.models.software_component import SoftwareComponent
from nexussim_server import util

from nexussim_server.models.compute import Compute  # noqa: E501
from nexussim_server.models.network import Network  # noqa: E501
from nexussim_server.models.software_component import SoftwareComponent  # noqa: E501

class ServiceChain(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, version=None, computes=None, networks=None, software_components=None):  # noqa: E501
        """ServiceChain - a model defined in OpenAPI

        :param name: The name of this ServiceChain.  # noqa: E501
        :type name: str
        :param description: The description of this ServiceChain.  # noqa: E501
        :type description: str
        :param version: The version of this ServiceChain.  # noqa: E501
        :type version: str
        :param computes: The computes of this ServiceChain.  # noqa: E501
        :type computes: List[Compute]
        :param networks: The networks of this ServiceChain.  # noqa: E501
        :type networks: List[Network]
        :param software_components: The software_components of this ServiceChain.  # noqa: E501
        :type software_components: List[SoftwareComponent]
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'version': str,
            'computes': List[Compute],
            'networks': List[Network],
            'software_components': List[SoftwareComponent]
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'version': 'version',
            'computes': 'computes',
            'networks': 'networks',
            'software_components': 'software components'
        }

        self._name = name
        self._description = description
        self._version = version
        self._computes = computes
        self._networks = networks
        self._software_components = software_components

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceChain':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The service_chain of this ServiceChain.  # noqa: E501
        :rtype: ServiceChain
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ServiceChain.

        The name of the application service chain  # noqa: E501

        :return: The name of this ServiceChain.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ServiceChain.

        The name of the application service chain  # noqa: E501

        :param name: The name of this ServiceChain.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ServiceChain.

        A free form field to put a human readable description of this service chain  # noqa: E501

        :return: The description of this ServiceChain.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ServiceChain.

        A free form field to put a human readable description of this service chain  # noqa: E501

        :param description: The description of this ServiceChain.
        :type description: str
        """

        self._description = description

    @property
    def version(self) -> str:
        """Gets the version of this ServiceChain.

        The version of the application chain  # noqa: E501

        :return: The version of this ServiceChain.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this ServiceChain.

        The version of the application chain  # noqa: E501

        :param version: The version of this ServiceChain.
        :type version: str
        """

        self._version = version

    @property
    def computes(self) -> List[Compute]:
        """Gets the computes of this ServiceChain.


        :return: The computes of this ServiceChain.
        :rtype: List[Compute]
        """
        return self._computes

    @computes.setter
    def computes(self, computes: List[Compute]):
        """Sets the computes of this ServiceChain.


        :param computes: The computes of this ServiceChain.
        :type computes: List[Compute]
        """
        if computes is not None and len(computes) < 1:
            raise ValueError("Invalid value for `computes`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._computes = computes

    @property
    def networks(self) -> List[Network]:
        """Gets the networks of this ServiceChain.


        :return: The networks of this ServiceChain.
        :rtype: List[Network]
        """
        return self._networks

    @networks.setter
    def networks(self, networks: List[Network]):
        """Sets the networks of this ServiceChain.


        :param networks: The networks of this ServiceChain.
        :type networks: List[Network]
        """
        if networks is not None and len(networks) < 1:
            raise ValueError("Invalid value for `networks`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._networks = networks

    @property
    def software_components(self) -> List[SoftwareComponent]:
        """Gets the software_components of this ServiceChain.


        :return: The software_components of this ServiceChain.
        :rtype: List[SoftwareComponent]
        """
        return self._software_components

    @software_components.setter
    def software_components(self, software_components: List[SoftwareComponent]):
        """Sets the software_components of this ServiceChain.


        :param software_components: The software_components of this ServiceChain.
        :type software_components: List[SoftwareComponent]
        """
        if software_components is not None and len(software_components) < 1:
            raise ValueError("Invalid value for `software_components`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._software_components = software_components
