from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server import util


class SimulationStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, kpis=None):  # noqa: E501
        """SimulationStatus - a model defined in OpenAPI

        :param status: The status of this SimulationStatus.  # noqa: E501
        :type status: str
        :param kpis: The kpis of this SimulationStatus.  # noqa: E501
        :type kpis: List[object]
        """
        self.openapi_types = {
            'status': str,
            'kpis': List[object]
        }

        self.attribute_map = {
            'status': 'status',
            'kpis': 'kpis'
        }

        self._status = status
        self._kpis = kpis

    @classmethod
    def from_dict(cls, dikt) -> 'SimulationStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The simulation_status of this SimulationStatus.  # noqa: E501
        :rtype: SimulationStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this SimulationStatus.


        :return: The status of this SimulationStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this SimulationStatus.


        :param status: The status of this SimulationStatus.
        :type status: str
        """
        allowed_values = ["running", "finished", "error", "unknown"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def kpis(self) -> List[object]:
        """Gets the kpis of this SimulationStatus.


        :return: The kpis of this SimulationStatus.
        :rtype: List[object]
        """
        return self._kpis

    @kpis.setter
    def kpis(self, kpis: List[object]):
        """Sets the kpis of this SimulationStatus.


        :param kpis: The kpis of this SimulationStatus.
        :type kpis: List[object]
        """

        self._kpis = kpis
