from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nexussim_server.models.base_model import Model
from nexussim_server.models.load import Load
from nexussim_server.models.software_component_segments_inner import SoftwareComponentSegmentsInner
from nexussim_server import util

from nexussim_server.models.load import Load  # noqa: E501
from nexussim_server.models.software_component_segments_inner import SoftwareComponentSegmentsInner  # noqa: E501

class SoftwareComponent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, description=None, base_load=None, segments=None):  # noqa: E501
        """SoftwareComponent - a model defined in OpenAPI

        :param id: The id of this SoftwareComponent.  # noqa: E501
        :type id: str
        :param description: The description of this SoftwareComponent.  # noqa: E501
        :type description: str
        :param base_load: The base_load of this SoftwareComponent.  # noqa: E501
        :type base_load: Load
        :param segments: The segments of this SoftwareComponent.  # noqa: E501
        :type segments: List[SoftwareComponentSegmentsInner]
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'base_load': Load,
            'segments': List[SoftwareComponentSegmentsInner]
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'base_load': 'base_load',
            'segments': 'segments'
        }

        self._id = id
        self._description = description
        self._base_load = base_load
        self._segments = segments

    @classmethod
    def from_dict(cls, dikt) -> 'SoftwareComponent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The software_component of this SoftwareComponent.  # noqa: E501
        :rtype: SoftwareComponent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this SoftwareComponent.


        :return: The id of this SoftwareComponent.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this SoftwareComponent.


        :param id: The id of this SoftwareComponent.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this SoftwareComponent.

        A free form field to put a human readable description of the software component  # noqa: E501

        :return: The description of this SoftwareComponent.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this SoftwareComponent.

        A free form field to put a human readable description of the software component  # noqa: E501

        :param description: The description of this SoftwareComponent.
        :type description: str
        """

        self._description = description

    @property
    def base_load(self) -> Load:
        """Gets the base_load of this SoftwareComponent.


        :return: The base_load of this SoftwareComponent.
        :rtype: Load
        """
        return self._base_load

    @base_load.setter
    def base_load(self, base_load: Load):
        """Sets the base_load of this SoftwareComponent.


        :param base_load: The base_load of this SoftwareComponent.
        :type base_load: Load
        """

        self._base_load = base_load

    @property
    def segments(self) -> List[SoftwareComponentSegmentsInner]:
        """Gets the segments of this SoftwareComponent.


        :return: The segments of this SoftwareComponent.
        :rtype: List[SoftwareComponentSegmentsInner]
        """
        return self._segments

    @segments.setter
    def segments(self, segments: List[SoftwareComponentSegmentsInner]):
        """Sets the segments of this SoftwareComponent.


        :param segments: The segments of this SoftwareComponent.
        :type segments: List[SoftwareComponentSegmentsInner]
        """
        if segments is None:
            raise ValueError("Invalid value for `segments`, must not be `None`")  # noqa: E501
        if segments is not None and len(segments) < 1:
            raise ValueError("Invalid value for `segments`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._segments = segments
